version: '2'
services:
  consul-ui:
    build: ./consul
    command: >
      agent
      -dev
      -ui
      -client 0.0.0.0
    ports:
      - "8500:8500"

  consul:
    build: ./consul
    expose:
      - "8500"
    command: >
      agent
      -dev
      -client 0.0.0.0
      -join consul-ui

  app:
    build: ./docker-node-hello
    links:
      - consul
