version: '2'
services:
  consul-ui:
    build: ./consul
    command: >
      agent
      -dev
      -ui
      -client 0.0.0.0
    ports:
      - "53"
      - "8300-8302"
      - "8400"
      - "8500:8500"
      - "8600"
    restart: always

  consul:
    build: ./consul
    expose:
      - "8500"
    command: >
      agent
      -dev
      -client 0.0.0.0
      -join consul-ui
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    links:
      - consul
    restart: always

  app:
    build: ./docker-node-hello
    ports:
      - 8080
    restart: always
    links:
      - consul
